# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Sat May 18 18:04:51 2013
#      by: PyQt4 UI code generator 4.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(606, 291)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 481, 41))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setSizeConstraint(QtGui.QLayout.SetNoConstraint)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.playPushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.playPushButton.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Actions-player-play-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.playPushButton.setIcon(icon)
        self.playPushButton.setObjectName(_fromUtf8("playPushButton"))
        self.horizontalLayout.addWidget(self.playPushButton)
        self.pausePushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.pausePushButton.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Actions-player-pause-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.pausePushButton.setIcon(icon1)
        self.pausePushButton.setObjectName(_fromUtf8("pausePushButton"))
        self.horizontalLayout.addWidget(self.pausePushButton)
        self.stopPushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.stopPushButton.setText(_fromUtf8(""))
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Actions-player-stop-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.stopPushButton.setIcon(icon2)
        self.stopPushButton.setObjectName(_fromUtf8("stopPushButton"))
        self.horizontalLayout.addWidget(self.stopPushButton)
        self.prevPushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.prevPushButton.setText(_fromUtf8(""))
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Actions-green-arrow-left-end-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.prevPushButton.setIcon(icon3)
        self.prevPushButton.setObjectName(_fromUtf8("prevPushButton"))
        self.horizontalLayout.addWidget(self.prevPushButton)
        self.nextPushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.nextPushButton.setText(_fromUtf8(""))
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Actions-green-arrow-right-end-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.nextPushButton.setIcon(icon4)
        self.nextPushButton.setObjectName(_fromUtf8("nextPushButton"))
        self.horizontalLayout.addWidget(self.nextPushButton)
        self.addPushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.addPushButton.setText(_fromUtf8(""))
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Actions-list-add-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.addPushButton.setIcon(icon5)
        self.addPushButton.setObjectName(_fromUtf8("addPushButton"))
        self.horizontalLayout.addWidget(self.addPushButton)
        self.downloadPushButton = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.downloadPushButton.setText(_fromUtf8(""))
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("icons/Button-Download-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.On)
        self.downloadPushButton.setIcon(icon6)
        self.downloadPushButton.setObjectName(_fromUtf8("downloadPushButton"))
        self.horizontalLayout.addWidget(self.downloadPushButton)
        self.progressSlider = QtGui.QSlider(self.horizontalLayoutWidget)
        self.progressSlider.setOrientation(QtCore.Qt.Horizontal)
        self.progressSlider.setObjectName(_fromUtf8("progressSlider"))
        self.horizontalLayout.addWidget(self.progressSlider)
        self.playlistTableWidget = QtGui.QTableWidget(self.centralwidget)
        self.playlistTableWidget.setGeometry(QtCore.QRect(0, 40, 601, 201))
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.playlistTableWidget.sizePolicy().hasHeightForWidth())
        self.playlistTableWidget.setSizePolicy(sizePolicy)
        self.playlistTableWidget.setAutoScrollMargin(3)
        self.playlistTableWidget.setEditTriggers(QtGui.QAbstractItemView.NoEditTriggers)
        self.playlistTableWidget.setShowGrid(True)
        self.playlistTableWidget.setObjectName(_fromUtf8("playlistTableWidget"))
        self.playlistTableWidget.setColumnCount(3)
        self.playlistTableWidget.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        font = QtGui.QFont()
        font.setPointSize(11)
        item.setFont(font)
        self.playlistTableWidget.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.playlistTableWidget.setHorizontalHeaderItem(1, item)
        item = QtGui.QTableWidgetItem()
        self.playlistTableWidget.setHorizontalHeaderItem(2, item)
        self.timeLabel = QtGui.QLabel(self.centralwidget)
        self.timeLabel.setGeometry(QtCore.QRect(480, 10, 121, 17))
        self.timeLabel.setText(_fromUtf8(""))
        self.timeLabel.setObjectName(_fromUtf8("timeLabel"))
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 606, 25))
        self.menubar.setMouseTracking(False)
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuTest = QtGui.QMenu(self.menubar)
        self.menuTest.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.menuTest.setMouseTracking(True)
        self.menuTest.setFocusPolicy(QtCore.Qt.TabFocus)
        self.menuTest.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.menuTest.setAcceptDrops(False)
        self.menuTest.setToolTip(_fromUtf8(""))
        self.menuTest.setStatusTip(_fromUtf8(""))
        self.menuTest.setWhatsThis(_fromUtf8(""))
        self.menuTest.setAccessibleName(_fromUtf8(""))
        self.menuTest.setAccessibleDescription(_fromUtf8(""))
        self.menuTest.setObjectName(_fromUtf8("menuTest"))
        self.menuPlayback = QtGui.QMenu(self.menubar)
        self.menuPlayback.setObjectName(_fromUtf8("menuPlayback"))
        self.menuPlaylist = QtGui.QMenu(self.menubar)
        self.menuPlaylist.setObjectName(_fromUtf8("menuPlaylist"))
        self.menuSort = QtGui.QMenu(self.menuPlaylist)
        self.menuSort.setObjectName(_fromUtf8("menuSort"))
        self.menuHelp = QtGui.QMenu(self.menubar)
        self.menuHelp.setObjectName(_fromUtf8("menuHelp"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionQuite = QtGui.QAction(MainWindow)
        self.actionQuite.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionQuite.setObjectName(_fromUtf8("actionQuite"))
        self.actionRepeat = QtGui.QAction(MainWindow)
        self.actionRepeat.setSoftKeyRole(QtGui.QAction.NoSoftKey)
        self.actionRepeat.setObjectName(_fromUtf8("actionRepeat"))
        self.actionRandom = QtGui.QAction(MainWindow)
        self.actionRandom.setObjectName(_fromUtf8("actionRandom"))
        self.actionStop_after_current_song = QtGui.QAction(MainWindow)
        self.actionStop_after_current_song.setObjectName(_fromUtf8("actionStop_after_current_song"))
        self.actionPlay = QtGui.QAction(MainWindow)
        self.actionPlay.setObjectName(_fromUtf8("actionPlay"))
        self.actionPause = QtGui.QAction(MainWindow)
        self.actionPause.setObjectName(_fromUtf8("actionPause"))
        self.actionStop = QtGui.QAction(MainWindow)
        self.actionStop.setObjectName(_fromUtf8("actionStop"))
        self.actionPrevious = QtGui.QAction(MainWindow)
        self.actionPrevious.setObjectName(_fromUtf8("actionPrevious"))
        self.actionNext = QtGui.QAction(MainWindow)
        self.actionNext.setObjectName(_fromUtf8("actionNext"))
        self.actionViewText = QtGui.QAction(MainWindow)
        self.actionViewText.setObjectName(_fromUtf8("actionViewText"))
        self.actionBy_title = QtGui.QAction(MainWindow)
        self.actionBy_title.setObjectName(_fromUtf8("actionBy_title"))
        self.actionBy_artist = QtGui.QAction(MainWindow)
        self.actionBy_artist.setObjectName(_fromUtf8("actionBy_artist"))
        self.actionBy_duration = QtGui.QAction(MainWindow)
        self.actionBy_duration.setObjectName(_fromUtf8("actionBy_duration"))
        self.actionShuffle = QtGui.QAction(MainWindow)
        self.actionShuffle.setObjectName(_fromUtf8("actionShuffle"))
        self.actionRefresh = QtGui.QAction(MainWindow)
        self.actionRefresh.setObjectName(_fromUtf8("actionRefresh"))
        self.actionAbout = QtGui.QAction(MainWindow)
        self.actionAbout.setObjectName(_fromUtf8("actionAbout"))
        self.actionLogin = QtGui.QAction(MainWindow)
        self.actionLogin.setObjectName(_fromUtf8("actionLogin"))
        self.actionSavePlaylist = QtGui.QAction(MainWindow)
        self.actionSavePlaylist.setObjectName(_fromUtf8("actionSavePlaylist"))
        self.actionOpenPlaylist = QtGui.QAction(MainWindow)
        self.actionOpenPlaylist.setObjectName(_fromUtf8("actionOpenPlaylist"))
        self.actionSimple = QtGui.QAction(MainWindow)
        self.actionSimple.setObjectName(_fromUtf8("actionSimple"))
        self.actionAddSongs = QtGui.QAction(MainWindow)
        self.actionAddSongs.setObjectName(_fromUtf8("actionAddSongs"))
        self.actionSingle = QtGui.QAction(MainWindow)
        self.actionSingle.setObjectName(_fromUtf8("actionSingle"))
        self.menuTest.addAction(self.actionLogin)
        self.menuTest.addAction(self.actionSavePlaylist)
        self.menuTest.addAction(self.actionOpenPlaylist)
        self.menuTest.addAction(self.actionQuite)
        self.menuPlayback.addAction(self.actionSingle)
        self.menuPlayback.addAction(self.actionRepeat)
        self.menuPlayback.addAction(self.actionRandom)
        self.menuPlayback.addSeparator()
        self.menuPlayback.addAction(self.actionPlay)
        self.menuPlayback.addAction(self.actionPause)
        self.menuPlayback.addAction(self.actionStop)
        self.menuPlayback.addAction(self.actionPrevious)
        self.menuPlayback.addAction(self.actionNext)
        self.menuPlayback.addAction(self.actionViewText)
        self.menuSort.addAction(self.actionBy_title)
        self.menuSort.addAction(self.actionBy_artist)
        self.menuSort.addAction(self.actionBy_duration)
        self.menuPlaylist.addAction(self.menuSort.menuAction())
        self.menuPlaylist.addAction(self.actionAddSongs)
        self.menuHelp.addAction(self.actionAbout)
        self.menubar.addAction(self.menuTest.menuAction())
        self.menubar.addAction(self.menuPlayback.menuAction())
        self.menubar.addAction(self.menuPlaylist.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "Vkontakte audio player", None))
        self.stopPushButton.setToolTip(_translate("MainWindow", "Play", None))
        item = self.playlistTableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Artist", None))
        item = self.playlistTableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Title", None))
        item = self.playlistTableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Duration", None))
        self.menuTest.setTitle(_translate("MainWindow", "File", None))
        self.menuPlayback.setTitle(_translate("MainWindow", "Playback", None))
        self.menuPlaylist.setTitle(_translate("MainWindow", "Playlist", None))
        self.menuSort.setTitle(_translate("MainWindow", "Sort", None))
        self.menuHelp.setTitle(_translate("MainWindow", "Help", None))
        self.actionQuite.setText(_translate("MainWindow", "Quite", None))
        self.actionRepeat.setText(_translate("MainWindow", "Repeat", None))
        self.actionRandom.setText(_translate("MainWindow", "Random", None))
        self.actionStop_after_current_song.setText(_translate("MainWindow", "Stop after current track", None))
        self.actionPlay.setText(_translate("MainWindow", "Play", None))
        self.actionPause.setText(_translate("MainWindow", "Pause", None))
        self.actionStop.setText(_translate("MainWindow", "Stop", None))
        self.actionPrevious.setText(_translate("MainWindow", "Previous", None))
        self.actionNext.setText(_translate("MainWindow", "Next", None))
        self.actionViewText.setText(_translate("MainWindow", "View text", None))
        self.actionBy_title.setText(_translate("MainWindow", "By title", None))
        self.actionBy_artist.setText(_translate("MainWindow", "By artist", None))
        self.actionBy_duration.setText(_translate("MainWindow", "By duration", None))
        self.actionShuffle.setText(_translate("MainWindow", "Shuffle", None))
        self.actionRefresh.setText(_translate("MainWindow", "Refresh", None))
        self.actionAbout.setText(_translate("MainWindow", "About", None))
        self.actionLogin.setText(_translate("MainWindow", "Login", None))
        self.actionSavePlaylist.setText(_translate("MainWindow", "Save playlist", None))
        self.actionOpenPlaylist.setText(_translate("MainWindow", "Open playlist", None))
        self.actionSimple.setText(_translate("MainWindow", "Simple", None))
        self.actionAddSongs.setText(_translate("MainWindow", "Add songs", None))
        self.actionSingle.setText(_translate("MainWindow", "Single", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

